FORMAT: 1A
HOST: https://lk.vectoranalytics.ru/

# vectoranalytics

Описание API Вектора

## Внешнее API

### Get token for user [GET]

Выделить токен для пользователя
     /oauth?client_id=0d07c30a399ffd893b59ca770ded0b6c&state=some_text

Переадресация на   
    /app/token/?token=user_token&url=app_callback_url&state=some_text
    

## Template [/template.php]

### Draft API [GET]

+ Request (application/json)

        {
            "action": "get"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }


## init.php [/init.php]

### Main script Vector [GET]
Запрос который приходит из браузера клиента

+ Request (application/json)

        {
            "src": 1,
            "ac": 1,
            "cid": 3367511,
            "sid": 5702182,
            "aid": 193415,
            "gclid": "3af69c5d4410be858554945a5ae941fe",
            "google_cid": "878822566.1444994565",
            "yandex_cid": "14630587861015199503",
            "chaser_cid": 0,
            "referrer": "",
            "landing_page": "http://muravino.ru/",
            "r": "1484918118575",
            "callback": "CallbackRegistry.f026698512794595564",
            "tab": "a:1:top:0:x:600:y:726"
        }
        
+ Response 200 (text/javascript)

            {
                "cid": 3367511,
                "domain": "muravino.ru",
                "js_replace": 1,
                "leads": [],
                "ph": 74996498233,
                "promo": {},
                "rr": 1,
                "sid": 6112935,
                "tpl": [],
                "widget": {
                    "is_display_on_site": true,
                    "message": "",
                    "color": {"r": 255, "g": 255, "b": 255, "a": 1},
                    "ui":{
                        "button": {
                            "position": {
                                "bottom": {
                                    "value": 80,
                                    "unit": {
                                        "name": "px"
                                    }
                                },
                                "right": {
                                    "value": 100,
                                    "unit":{
                                        "type_name": "px"
                                    }
                                }
                            },
                            "text": "Оставьте заявку",
                            "is_display": true
                        },
                        "form": {
                            "description": "Оставьте свой номер и мы вам перезвоним",
                            "control_text": "Позвоните мне",
                            "is_display_shadow": false,
                            "brand_icon": "url/text",
                            "is_display_brand_icon": false,
                            "is_display_countdown": false,
                            "countdown": 60,
                            "is_show_vector_logo": true,
                            "is_show_free_of_charge": true,
                            "is_show_speech_record": true,
                            "is_border_radius": false,
                            "is_display_agreement_link": false,
                            "agreement_link": ""
                        }, 
                        "background": {
                            "color": {"r": 255, "g": 255, "b": 255, "a": 0.5},
                            "is_display": true
                        }
                    },
                    "settings": {
                        "is_use_closing": true,
                        "is_use_once_day": true,
                        "is_use_once_session": true,
                        "is_use_timeout": true,
                        "timeout": 60,
                        "weekdays":{
                          "is_weekday": false,
                          "weekday_next": "Понедельник с 9:00 до 18:00"
                        },
                        "show_form": "VectorShowForm"
                    }
                }
            }



        
            
## Deals [/api/site/deals/action.php]

### Get deals list [GET /api/site/deals/action.php?action=get]

Получить список обращений

+ Request (application/json)

        {
            "action": "get",
            "site_id": 261,
            "filters": {
                "categories": [],
                "client_numbers": [],
                "comment": null,
                "dates": {
                    "from": "05.04.2017",
                    "to": "27.04.2017"
                },
                "deal_ids": [],
                "deal_type_id": 358,
                "deal_values": [],
                "event_types": [],
                "is_my_deals": false,
                "magic_string": "",
                "missed": [],
                "pagination": {
                    "count_rows": 50,
                    "page_number": 1
                },
                "phones": [],
                "repeated": [],
                "tags": null,
                "utms": []
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "calls":[
                {
                    "abonent_phone": "79639785897",
                    "ad_channels": null,
                    "audio": {
                        "json": "https://lk.vectoranalytics.ru/audio/mp3_v9/6296/2017-11-10_12.16.37_from_74986282670_to_74996489701.json",
                        "link": "https://lk.vectoranalytics.ru/api/audio/action.php?h1=5670bec2-ef87-11e6-bf90-448a5bd87a8d&h2=7c30e212-c5f8-11e7-b8cb-448a5bd87a8d&type=.mp3"
                    },
                    "category_id": 460,
                    "channel_name": "студио12-KR Propert-topnovostr",
                    "city": "",
                    "client_email": "",
                    "client_name": "",
                    "client_phone": "",
                    "comment": "",
                    "adm_comment": "",
                    "date": "2017-04-27 19:41:49",
                    "deal_days_gap": 0,
                    "deal_processing": {
                        "id": 763,
                        "name": "Полная обработка"
                    },
                    "duration": "00:02:40",
                    "type": {
                        "id": 661,
                        "name": "Звонок"
                    },
                    "subtype_id": {
                        "id": 668,
                        "name": "Входящий звонок"
                    },
                    "gender": 0,
                    "id": 128964,
                    "ip": null,
                    "is_delay": false,
                    "is_manual": 0,
                    "is_missed": 0,
                    "is_repeated": 1,
                    "is_result": false,
                    "is_spam": 0,
                    "is_save": true,
                    "keyword": null,
                    "landing_page": "",
                    "manager_name": "",
                    "manager_value": null,
                    "promo": "",
                    "provider": {
                        "id": 384,
                        "name": "Вектор"
                    },
                    "referrer": "",
                    "setup_time_ms": 4246,
                    "site_id": 261,
                    "system_operator_id": 63,
                    "tag_str":  "",
                    "tags": [
                    ],
                    "trigger": null,
                    "utm_campaign": "",
                    "utm_content": "",
                    "utm_medium": "",
                    "utm_source": "",
                    "utm_term": "",
                    "value": 0,
                    "virtual_phone": "74996495086",
                    "url_conversion": "",
                    "save_deals_mechanics_state": 0
                    }
            ],
            "count": "1059",
            "deal_type_id": 358,
            "managers": [
                {
                    "site_id": 261,
                    "values": []
                }
            ],
            "pagination": {
                "begin_page": 1,
                "count_pages": 22,
                "current_page": 1,
                "end_page": 22,
                "first_page": 0,
                "last_page": 0,
                "max_shown_pages": 31
            },
            "tags": [
                {
                    "site_id": 261,
                    "values": []
                }
            ]
        }
        
### Save deal [GET /api/site/deals/action.php?action=save]

Сохранение данных по обращению

+ Request (application/json)

        {
            "action": "save",
            "site_id": 261,
            "deal":{
                    "abonent_phone": "79639785897",
                    "ad_channels": null,
                    "audio": {
                        "json": "https://lk.vectoranalytics.ru/audio/mp3_v9/6296/2017-11-10_12.16.37_from_74986282670_to_74996489701.json",
                        "link": "https://lk.vectoranalytics.ru/api/audio/action.php?h1=5670bec2-ef87-11e6-bf90-448a5bd87a8d&h2=7c30e212-c5f8-11e7-b8cb-448a5bd87a8d&type=.mp3"
                    },
                    "category_id": 460,
                    "channel_name": "студио12-KR Propert-topnovostr",
                    "city": "",
                    "client_email": "",
                    "client_name": "",
                    "client_phone": "",
                    "comment": "",
                    "adm_comment": "",
                    "date": "2017-04-27 19:41:49",
                    "deal_days_gap": 0,
                    "deal_processing": {
                        "id": 763,
                        "name": "Полная обработка"
                    },
                    "duration": "00:02:40",
                    "type": {
                        "id": 661,
                        "name": "Звонок"
                    },
                    "subtype_id": {
                        "id": 668,
                        "name": "Входящий звонок"
                    },
                    "gender": 0,
                    "id": 128964,
                    "ip": null,
                    "is_delay": false,
                    "is_manual": 0,
                    "is_missed": 0,
                    "is_repeated": 1,
                    "is_result": false,
                    "is_spam": 0,
                    "is_save": true,
                    "keyword": null,
                    "landing_page": "",
                    "manager_name": "",
                    "manager_value": null,
                    "promo": "",
                    "provider": {
                        "id": 384,
                        "name": "Вектор"
                    },
                    "referrer": "",
                    "setup_time_ms": 4246,
                    "site_id": 261,
                    "system_operator_id": 63,
                    "tag_str":  "",
                    "tags": [
                    ],
                    "trigger": null,
                    "utm_campaign": "",
                    "utm_content": "",
                    "utm_medium": "",
                    "utm_source": "",
                    "utm_term": "",
                    "value": 0,
                    "virtual_phone": "74996495086",
                    "save_deals_mechanics_state": 0
                    }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "call":{
                    "abonent_phone": "79639785897",
                    "ad_channels": null,
                    "audio": {
                        "json": "https://lk.vectoranalytics.ru/audio/mp3_v9/6296/2017-11-10_12.16.37_from_74986282670_to_74996489701.json",
                        "link": "https://lk.vectoranalytics.ru/api/audio/action.php?h1=5670bec2-ef87-11e6-bf90-448a5bd87a8d&h2=7c30e212-c5f8-11e7-b8cb-448a5bd87a8d&type=.mp3"
                    },
                    "category_id": 460,
                    "channel_name": "студио12-KR Propert-topnovostr",
                    "city": "",
                    "client_email": "",
                    "client_name": "",
                    "client_phone": "",
                    "comment": "",
                    "adm_comment": "",
                    "date": "2017-04-27 19:41:49",
                    "deal_days_gap": 0,
                    "deal_processing": {
                        "id": 763,
                        "name": "Полная обработка"
                    },
                    "duration": "00:02:40",
                    "type": {
                        "id": 661,
                        "name": "Звонок"
                    },
                    "subtype_id": {
                        "id": 668,
                        "name": "Входящий звонок"
                    },
                    "gender": 0,
                    "id": 128964,
                    "ip": null,
                    "is_delay": false,
                    "is_manual": 0,
                    "is_missed": 0,
                    "is_repeated": 1,
                    "is_result": false,
                    "is_spam": 0,
                    "is_save": true,
                    "keyword": null,
                    "landing_page": "",
                    "manager_name": "",
                    "manager_value": null,
                    "promo": "",
                    "provider": {
                        "id": 384,
                        "name": "Вектор"
                    },
                    "referrer": "",
                    "setup_time_ms": 4246,
                    "site_id": 261,
                    "system_operator_id": 63,
                    "tag_str":  "",
                    "tags": [
                    ],
                    "trigger": null,
                    "utm_campaign": "",
                    "utm_content": "",
                    "utm_medium": "",
                    "utm_source": "",
                    "utm_term": "",
                    "value": 0,
                    "virtual_phone": "74996495086",
                    "save_deals_mechanics_state": 0
                    }
        }


### Get deals list for system operator [GET /api/site/deals/action.php?action=get_for_operator]

Получить список обращений по заданному проекту для данного номера абонента

+ Request (application/json)

        {
            "action": "get_for_operator",
            "site_id": 261,
            "phone_int": 79639785897
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "deals": [
                {
                    "id": 128964,
                    "site_id": 261,
                    "start_date": "2017-04-27 19:41:49",
                    "processing": {
                        "client": {
                            "phone_int": "79639785897",
                            "email": "",
                            "name": "",
                            "phone": "",
                            "gender": 0
                        },
                        "category_id": 460,
                        "comment": "",
                        "adm_comment": "",
                        "is_delay": false,
                        "is_result": false,
                        "is_spam": 0,
                        "is_save": true,
                        "manager_name": "",
                        "manager_value": null,
                        "promo": "",
                        "tag_str":  "",
                        "tags": [
                        ],
                        "value": 0
                    },
                    "processing_type": {
                        "id": 763,
                        "name": "Полная обработка"
                    },
                    "traffic": {
                        "ad_channels": null,
                        "url_conversion": ""
                    },
                    "audio": {
                        "json": "https://lk.vectoranalytics.ru/audio/mp3_v9/6296/2017-11-10_12.16.37_from_74986282670_to_74996489701.json",
                        "link": "https://lk.vectoranalytics.ru/api/audio/action.php?h1=5670bec2-ef87-11e6-bf90-448a5bd87a8d&h2=7c30e212-c5f8-11e7-b8cb-448a5bd87a8d&type=.mp3"
                    },
                    "info": {
                        "channel_name": "студио12-KR Propert-topnovostr",
                        "duration": "00:02:40",
                        "type": {
                            "id": 661,
                            "name": "Звонок"
                        },
                        "subtype_id": {
                            "id": 668,
                            "name": "Входящий звонок"
                        },
                        "provider": {
                            "id": 384,
                            "name": "Вектор"
                        },
                        "is_manual": 0,
                        "is_missed": 0,
                        "is_repeated": 1,
                        "setup_time_ms": 4246,
                        "trigger": null,
                        "deal_days_gap": 0,
                        "save_deals_mechanics_state": 0
                    }
                }
            ],
            "managers": [
                {
                    "site_id": 261,
                    "values": []
                }
            ]
        }
        
## Tag [/api/tags/action.php]

### Get list tags [GET /api/tags/action.php?action=get]
Получаем список тегов для сайата

+ Request (application/json)

        {
            "action": "get",
            "site_id": 156
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "tags": [
                {
                "id": 733,
                "name": "реклама",
                "count_deals": 10,
                "state": 1
                }
            ]
        }
        
### Get tag info [GET /api/tags/action.php?action=get&tag_id=]
Получаем данные по одному тегу

+ Request (application/json)

        {
            "action": "get",
            "site_id": 156,
            "tag_id": 5
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "tag": {
                "id": 733,
                "name": "реклама",
                "count_deals": 10,
                "state": 1
            }
        }
        
### Save tag [GET /api/tags/action.php?action=save&tag_id=]

Сохраняем или добавляем тег

+ Request (application/json)

        {
            "action": "save",
            "site_id": 156,
            "tag": {
                "id": 733,
                "name": "реклама2",
                "count_deals": 10,
                "state": 1
            }
            
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "tag": {
                "id": 733,
                "name": "реклама2",
                "count_deals": 10,
                "state": 1
            }
        }
        
### Remove tag [GET /api/tags/action.php?action=remove&tag_id=]

Удаляем тег

+ Request (application/json)

        {
            "action": "remove",
            "site_id": 156,
            "tag_id": 733
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
### Restore tag [GET /api/tags/action.php?action=restore&tag_id=]

Восстанавливаем тег из удалённых

+ Request (application/json)

        {
            "action": "restore",
            "site_id": 156,
            "tag_id": 733
            
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
### Merge tags [GET /api/tags/action.php?action=merge]

Объединить теги

+ Request (application/json)

        {
            "action": "merge",
            "site_id": 156,
            "tag_slave_id": 10,
            "tag_master_id": 30
            
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
## Group phones [/api/channels/action.php]

### Get list group phones [GET /api/channels/action.php?action=get]

Получение списка Групп телефонов

+ Request (application/json)

        {
            "action": "get",
            "site_id": 156
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "channels": [{
                "id": 733,
                "name": "hq.com.ru - рекламная",
                "state": 1,
                "layout_id": 1301,
                "is_on_site": 1, 
                "is_static": 0,
                "is_online": 1,
                "ads": 1,
                "ch_max_lifetime": 0,
                "type_max_lifetime": 1321,
                "site_max_lifetime": 1800,
                "redirect_script_id": 223,
                "count_phones": 4,
                "count_phones_add": 5
            }]
        }
        
### Get group phones info [GET /api/channels/action.php?action=get&channel_id=]

Получение информации по одной Группе телефонов

+ Request (application/json)

        {
            "action": "get",
            "site_id": "{site_id}",
            "channel_id": "{channel_id}"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "channels": [
                {
                    "id": 733,
                    "name": "hq.com.ru - рекламная",
                    "state": 1,
                    "layout_id": 1301,
                    "is_on_site": 1, 
                    "is_static": 0,
                    "is_online": 1,
                    "ads": 1,
                    "ch_max_lifetime": 0,
                    "type_max_lifetime": 1321,
                    "site_max_lifetime": 1800,
                    "redirect_script_id": 223,
                    "count_phones": 4,
                    "count_phones_add": 5,
                    "exceptions": {
                        "phones_count": 2,
                        "ips_count": 0
                    },
                    "phones": [{
                        "id": 2845,
                        "phone": "+7(499) 648-66-76",
                        "phone_int": 74996486676,
                        "start_date": "2017-08-22 18:54:33",
                        "is_rotation_phone_type": true,
                        "is_own_phone": false
                    }],
                    "utm_template": {
                        "id": 786,
                        "name": "Редактор правил"
                        },
                    "utms": [{
                        "id": 757,
                        "group_id": 0,
                        "type": "соответствует регулярному выражению",
                        "type_id": 5,
                        "utm": "Посадочная страница(Landing page)",
                        "field_type": "input",
                        "utm_group_id": 1,
                        "value": "utm_source",
                        "utm_id": 10,
                        "value_id": null
                    }],
                    "utm_template": {
                        "id": 786,
                        "name": "Редактор правил"
                    }
                }
            ]
        }
        
### Disconnect phone [GET /api/channels/action.php?action=disconnect]

Отключение виртуального номера телефона

+ Request (application/json)

        {
            "action": "disconnect",
            "site_id": 156,
            "channel_id": 10,
            "phone_id": 10
        } 
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
## Redirect [/api/site/action.php]

### Get list redirect script [GET /api/site/redirect_script/action.php?action=get]

Получаем список Сценариев перадресации

+ Request (application/json)

        {
            "action": "get",
            "site_id": 156
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "redirect_scripts": [
                {
                "id": 123,
                "name": "Базовый сценарий",
                "state": 1,
                "count_channels":5,
                "is_use_for_widget": true,
                "forward_mode_id": 611,
                "channels":[],
                "rules":[]
                }
            ]
        }

### Get redirect script info [GET /api/site/redirect_script/action.php?action=get&redirect_script_id=]

Получаем информацию по Сценарию перадресации

+ Request (application/json)

        {
            "action": "get",
            "site_id": 156,
            "redirect_script_id": 123
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "redirect_script": {
                "id": 123,
                "name": "Базовый сценарий",
                "state": 1,
                "count_channels":5,
                "is_use_for_widget": true,
                "forward_mode_id": 611,
                "channels":[],
                "rules":[]
                }
        }        

### Create redirect script [GET /api/site/redirect_script/action.php?action=create]

Создаём Сценарий перадресации

+ Request (application/json)

        {
            "action": "create",
            "site_id": 156,
            "redirect_script_id": null,
            "name": "Базовый сценарий",
            "rule": {
                "description": "Правило 1",
                "type_id": 2191,
                "site_sipid_history_id": 0,
                "redirect_number": "79639785897"
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "redirect_script": {
                "id": 123,
                "name": "Базовый сценарий",
                "state": 1,
                "count_channels":5,
                "is_use_for_widget": true,
                "channels":[],
                "rules":[]
                }
        }
        
        
### Save redirect script [GET /api/site/redirect_script/action.php?action=save]

Сохраняем Сценарий перадресации

+ Request (application/json)

        {
            "action": "save",
            "site_id": 156,
            "redirect_script_id": 123,
            "redirect_script_name": "Базовый сценарий",
            "forward_mode_id": 611
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "redirect_script": {
                "id": 123,
                "name": "Базовый сценарий",
                "state": 1,
                "count_channels":5,
                "is_use_for_widget": true,
                "forward_mode_id": 611,
                "channels":[],
                "rules":[]
                }
        }
        
### Get rule info for redirect script [GET /api/site/redirect_script/rule/action.php?action=get&id=]

Получаем информацию по одному Правилу перадресации

+ Request (application/json)

        {
            "action": "get",
            "site_id": 156,
            "redirect_script_id": 123,
            "rule_id": 456
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "redirect_script_id": 132,
            "rule": {
                "description": "Правило 1",
                "id": 456,
                "period": "always",
                "redirect_number": "79639785897",
                "timeout": 60,
                "type_id": 2191,
                "site_sipid_history_id": 0
            }
        }
        
### Delete rule from redirect script [GET /api/site/redirect_script/rule/action.php?action=remove]

Удаляем правило из Сценария переадресации

+ Request (application/json)

        {
            "action": "remove",
            "site_id": 156,
            "redirect_script_id": 123,
            "rule_id": 456
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
### Save rule info for redirect script [GET /api/site/redirect_script/rule/action.php?action=save&id=]

Сохраняем информацию по одному Правилу перадресации

+ Request (application/json)

        {
            "action": "save",
            "site_id": 156,
            "redirect_script_id": 132,
            "rule": {
                "description": "Правило 1",
                "id": 456,
                "period": "always",
                "redirect_number": "79639785897",
                "timeout": 60,
                "type_id": 2191,
                "site_sipid_history_id": 0
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "redirect_script_id": 132,
            "rule": {
                "description": "Правило 1",
                "id": 456,
                "period": "always",
                "redirect_number": "79639785897",
                "timeout": 60,
                "type_id": 2191,
                "site_sipid_history_id": 0
            }
        }
        
### Save Order Rules for Redirect Script [GET /api/site/redirect_script/rule/action.php?action=set_order]

Сохраняем сортировку правил для Сценария переадресации

+ Request (application/json)

        {
            "action": "set_order",
            "site_id": 156,
            "redirect_script_id": 10,
            "rules": [10, 11, 12, 13]
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }

## Goals [/api/goals/action.php]

### Get list goals [GET /api/goals/action.php?action=get&site_id=156]

Получаем список Целей

+ Request (application/json)

        {
            "action": "get",
            "site_id": 156
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "goals": [
                {
                    "id": 123,
                    "name": "ТестAPI",
                    "state": 1,
                    "type_id": 666,
                    "activation":{
                        "type_id": 3101, 
                        "element":{
                            "type_id": 20101,
                            "name": "test"
                        }
                    },
                    "fields": [
                        {
                            "id": 252,
                            "name": "",
                            "type_id": 681,
                            "element":{
                                "type_id": 20101,
                                "name": "test"
                            }
                        }
                    ]
                }
            ]
        }
        
        
### Get Goal info [GET /api/goals/action.php?action=get&site_id=156&goal_id=]

Получаем информацию по одной Цели

+ Request (application/json)

        {
            "action": "get",
            "site_id": 156,
            "id": 123
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "goals": [
                {
                    "id": 123,
                    "name": "ТестAPI",
                    "state": 1,
                    "type_id": 666,
                    "activation":{
                        "type_id": 3101, 
                        "element":{
                            "type_id": 20101,
                            "name": "test"
                        }
                    },
                    "fields": [
                        {
                            "id": 252,
                            "name": "",
                            "type_id": 681,
                            "element":{
                                "type_id": 20101,
                                "name": "test"
                            }
                        }
                    ]
                }
            ]
        }
        
### Save Goal [GET /api/goals/action.php?action=save&site_id=156&goal_id=]

Сохраняем информацию по Цели

+ Request (application/json)

        {
            "action": "save",
            "site_id": 156,
            "goal": {
                    "id": 123,
                    "name": "ТестAPI",
                    "state": 1,
                    "type_id": 666,
                    "activation":{
                        "type_id": 3101, 
                        "element":{
                            "type_id": 20101,
                            "name": "test"
                        }
                    },
                    "fields": [
                        {
                            "id": 252,
                            "name": "",
                            "type_id": 681,
                            "element":{
                                "type_id": 20101,
                                "name": "test"
                            }
                        }
                    ]
                }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "goal": {
                    "id": 123,
                    "name": "ТестAPI",
                    "state": 1,
                    "type_id": 666,
                    "activation":{
                        "type_id": 3101, 
                        "element":{
                            "type_id": 20101,
                            "name": "test"
                        }
                    },
                    "fields": [
                        {
                            "id": 252,
                            "name": "",
                            "type_id": 681,
                            "element":{
                                "type_id": 20101,
                                "name": "test"
                            }
                        }
                    ]
                }
        }

## Callback [/api/site/widget/callback/action.php]

### Get UI settings [GET /api/site/widget/callback/action.php?action=get_ui]

Получаем настройки оформления виджета

+ Request (application/json)

        {
            "action": "get_ui",
            "site_id": 15
        }
+ Response 200 (application/json)

        {   
            "error": null,
            "widget": {
                "id": 999,
                "color": {"r": 255, "g": 255, "b": 255, "a": 1},
                "button": {
                    "position": {
                        "bottom": {
                            "value": 80,
                            "unit": {
                                "type_id": 961,
                                "type_name": "px"
                            }
                        },
                        "right": {
                            "value": 100,
                            "unit":{
                                "type_id": 961,
                                "type_name": "px"
                            }
                        }
                    },             
                    "text": "Оставьте заявку",
                    "is_display": true
                },
                "form": {
                    "description": "Оставьте свой номер и мы вам перезвоним",
                    "control_text": "Позвоните мне",
                    "is_display_shadow": false,
                    "brand_icon": "url/text",
                    "is_display_brand_icon": false,
                    "is_display_countdown": false,
                    "countdown": 60,
                    "effect_id": 1731,
                    "is_show_vector_logo": true,
                    "is_show_free_of_charge": true,
                    "is_show_speech_record": true,
                    "is_border_radius": false,
                    "is_display_agreement_link": false,
                    "agreement_link": ""
                },
                "background": {
                    "color": {"r": 255, "g": 255, "b": 255, "a": 0.5},
                    "is_display": true
                }
            }
        }
        
### Save UI settings [GET /api/site/widget/callback/action.php?action=save_ui]

Сохраняем настройки оформления виджета

+ Request (application/json)

        {   
            "action": "save_ui",
            "site_id": 15,
            "widget": {
                "id": 999,
                "color": {"r": 255, "g": 255, "b": 255, "a": 1},
                "button": {
                    "position": {
                        "bottom": {
                            "value": 80,
                            "unit": {
                                "type_id": 961,
                                "type_name": "px"
                            }
                        },
                        "right": {
                            "value": 100,
                            "unit":{
                                "type_id": 961,
                                "type_name": "px"
                            }
                        }
                    }, 
                    "text": "Оставьте заявку",
                    "is_display": true
                },
                "form": {
                    "description": "Оставьте свой номер и мы вам перезвоним",
                    "control_text": "Позвоните мне",
                    "is_display_shadow": false,
                    "brand_icon": "url/text",
                    "is_display_brand_icon": false,
                    "is_display_countdown": false,
                    "countdown": 60,
                    "effect_id": 1731,
                    "is_show_vector_logo": true,
                    "is_show_free_of_charge": true,
                    "is_show_speech_record": true,
                    "is_border_radius": false,
                    "is_display_agreement_link": false,
                    "agreement_link": ""
                },
                "background": {
                    "color": {"r": 255, "g": 255, "b": 255, "a": 0.5},
                    "is_display": true
                }
            }
        }
+ Response 200 (application/json)

        {   
            "error": null,
            "widget": {
                "id": 999,
                "color": {"r": 255, "g": 255, "b": 255, "a": 1},
                "button": {
                    "position": {
                        "bottom": {
                            "value": 80,
                            "unit": {
                                "type_id": 961,
                                "type_name": "px"
                            }
                        },
                        "right": {
                            "value": 100,
                            "unit":{
                                "type_id": 961,
                                "type_name": "px"
                            }
                        }
                    }, 
                    "text": "Оставьте заявку",
                    "is_display": true
                },
                "form": {
                    "description": "Оставьте свой номер и мы вам перезвоним",
                    "control_text": "Позвоните мне",
                    "is_display_shadow": false,
                    "brand_icon": "url/text",
                    "is_display_brand_icon": false,
                    "is_display_countdown": false,
                    "countdown": 60,
                    "effect_id": 1731,
                    "is_show_vector_logo": true,
                    "is_show_free_of_charge": true,
                    "is_show_speech_record": true,
                    "is_border_radius": false,
                    "is_display_agreement_link": false,
                    "agreement_link": ""
                },
                "background": {
                    "color": {"r": 255, "g": 255, "b": 255, "a": 0.5},
                    "is_display": true
                }
            }
        }

        
### Get settings [GET /api/site/widget/callback/action.php?action=get_settings]

Получаем настройки показа виджета

+ Request (application/json)

        {
            "action": "get_settings",
            "site_id": 15
        }

+ Response 200 (application/json)

        {
            "error": null,
            "widget":{
                "id": 999,
                "is_display": true,
                "weekdays": [
                    {"id": 1, "name": "Понедельник", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 2, "name": "Вторник", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 3, "name": "Среда", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 4, "name": "Четверг", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 5, "name": "Пятница", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 6, "name": "Суббота", "is_active": false, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 7, "name": "Воскресенье", "is_active": false, "interval": {"from": "09:00", "to": "18:00"}}
                ],
                "is_use_closing": true,
                "is_use_once_day": true,
                "is_use_timeout": true,
                "redirect_script_id": 9999,
                "timeout": 60,
                "is_use_spamfilter": true,
                "is_use_once_session": true,
                "text_to_speech": {
                    "is_active": true,
                    "value": "Звонок с сайта"
                    },
                "show_form": "VectorShowForm"
                }
        }

### Save settings [GET /api/site/widget/callback/action.php?action=save_settings]

Сохраняем настройки показа виджета

+ Request (application/json)

        {
            "action": "save_settings",
            "site_id": 15,
            "widget":{
                "id": 999,
                "is_display": true,
                "weekdays": [
                    {"id": 1, "name": "Понедельник", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 2, "name": "Вторник", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 3, "name": "Среда", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 4, "name": "Четверг", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 5, "name": "Пятница", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 6, "name": "Суббота", "is_active": false, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 7, "name": "Воскресенье", "is_active": false, "interval": {"from": "09:00", "to": "18:00"}}
                ],
                "is_use_closing": true,
                "is_use_once_day": true,
                "is_use_timeout": true,
                "redirect_script_id": 9999,
                "timeout": 60,
                "is_use_spamfilter": true,
                "is_use_once_session": true,
                "text_to_speech": {
                    "is_active": true,
                    "value": "Звонок с сайта"
                    },
                "show_form": "VectorShowForm"
                }
        }

+ Response 200 (application/json)

        {   
            "error": null,
            "widget":{
                "id": 999,
                "is_display": true,
                "weekdays": [
                    {"id": 1, "name": "Понедельник", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 2, "name": "Вторник", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 3, "name": "Среда", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 4, "name": "Четверг", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 5, "name": "Пятница", "is_active": true, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 6, "name": "Суббота", "is_active": false, "interval": {"from": "09:00", "to": "18:00"}},
                    {"id": 7, "name": "Воскресенье", "is_active": false, "interval": {"from": "09:00", "to": "18:00"}}
                ],
                "is_use_closing": true,
                "is_use_once_day": true,
                "is_use_timeout": true,
                "redirect_script_id": 9999,
                "timeout": 60,
                "is_use_spamfilter": true,
                "is_use_once_session": true,
                "text_to_speech": {
                    "is_active": true,
                    "value": "Звонок с сайта"
                    }
                }
        }
        
### Call callback [GET /api/external/integrations/mtt/callback/action.php?action=send]

Вызываем этот скрипт когда пользователь вводит номер телефона и нажимает "Позвонить мне"

+ Request (application/json)

        {
            "action": "send",
            "aid": 123456,
            "sid": 98765432,
            "phone_int": 74951234567,
            "callback": "CallbackRegistry.f026698512794595564"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
### Call callback from Deals [GET /api/external/integrations/mtt/callback/action.php?action=send_callback_from_deals]

Делаем коллбэк со страницы Обращения

+ Request (application/json)

        {
            "action": "send_callback_from_deals",
            "phone_int": 74951234567,
            "site_id": 62,
            "site_redirect_script_id": 1413
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
## amoCRM [/api/amocrm/action.php]

### Get settings  [GET /api/amocrm/action.php?action=get]

Получаем настройки интеграции с amoCRM

+ Request (application/json)

        {
            "action": "get",
            "site_id": 89
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "amocrm":{
                "id": 7,
                "start_date": "12.07.2016",
                "subdomain": "martinholland",
                "user_hash": "d9bbcef1196ccddeaf521f7457201f2d",
                "user_login": "martin.dvigus@gmail.com",
                "is_send_calls": false,
                "is_send_leads": false,
                "is_send_cbs": false
            }
        }
        
### Save settings  [GET /api/amocrm/action.php?action=save]

Сохраняем настройки интеграции с amoCRM

+ Request (application/json)

        {
            "action": "save",
            "site_id": 89,
            "subdomain": "martinholland",
            "user_hash": "d9bbcef1196ccddeaf521f7457201f2d",
            "user_login": "martin.dvigus@gmail.com",
            "is_send_calls": false,
            "is_send_leads": false,
            "is_send_cbs": false
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "amocrm":{
                "id": 7,
                "start_date": "12.07.2016",
                "subdomain": "martinholland",
                "user_hash": "d9bbcef1196ccddeaf521f7457201f2d",
                "user_login": "martin.dvigus@gmail.com",
                "is_send_calls": false,
                "is_send_leads": false,
                "is_send_cbs": false
            }
        }
        
## Payment [/api/amo/tariff/action.php]

### Get tariff info [GET /api/amo/tariff/action.php?action=get_by_site]

Получаем информацию по тарифу для сайта

+ Request (application/json)

        {
            "action": "get_by_site",
            "site_id": 315
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "plan": null,
            "tariff":{
                "license":{
                    "base":{
                        "month_cost": 1000
                    },
                    "phones":{
                        "cost": 0,
                        "count": 1,
                        "month_cost": 0
                    },
                    "monthcost": 1000
                },
                "communication_services":{
                    "free_minutes":{
                        "cost_per_over_limit": 3,
                        "limit": 1000,
                        "over_limit": 1001
                    },
                    "phone_495":{
                        "cost": 500,
                        "count": 0,
                        "month_cost": 0
                    },
                    "phone_499":{
                        "cost": 400,
                        "count": 1,
                        "month_cost": 400
                    },
                    "phone_800":{
                        "cost": 1400,
                        "count": 0,
                        "month_cost": 0
                    },
                    "month_cost": 400
                },
                "extra_services":{
                    "deal_processing":{
                        "config_id": 1234,
                        "options": 
                        [
                            {
                                "id": 761,
                                "name": "Выключено",
                                "is_active": true,
                                "cost": 0
                            },
                            {
                                "id": 762,
                                "name": "Только категория",
                                "is_active": false,
                                "cost": 10
                            },
                            {
                                "id": 763,
                                "name": "Полная обработка",
                                "is_active": false,
                                "cost": 20
                            }
                        ]
                    },
                    "callback":{
                        "fix_russia": 1.99,
                        "mobile_russia": 2.99,
                        "fix_msk_spb": 1.15
                    },
                    "sip":{
                        "count": 3,
                        "cost": 150,
                        "month_cost": 450
                    },
                    "month_cost": 0
                },
                "month_cost": 1400
            }
        }
        
## Notifications [/api/user/notifications/action.php]

### Get notifications config [GET /api/user/notifications/action.php?action=get]

Получаем конфигурацию уведомлений для всех сайтов

+ Request (application/json)

        {
            "action": "get"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "sites":[
                {
                "id": 16,
                "name": "www.dommill.ru",
                "description": "Квартал Миллениум",
                "owner_id": 155,
                "access": 1013,
                "notifications":[
                    {
                    "id": 15,
                    "channel_id": 971,
                    "type_id": 982
                    }
                ]
                }   
            ]
        }
        
### Add notification [GET /api/user/notifications/action.php?action=add]

Добавляем уведомление

+ Request (application/json)

        {
            "action": "add",
            "site_id": 16,
            "notification": {
                "channel_id": 972,
                "type_id": 981
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "notification": {
                "id": 16,
                "channel_id": 972,
                "type_id": 981
            }
        }
        
### Remove notification [GET /api/user/notifications/action.php?action=remove]

Удаляем уведомление

+ Request (application/json)

        {
            "action": "remove",
            "site_id": 16,
            "notification": {
                "id": 16
             }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
## Exceptions [/api/ip/action.php]

### Get IP exceptions list [GET /api/ip/action.php?action=get]

Получить список исключённых ip-адресов

+ Request (application/json)

        {
            "action": "get",
            "site_id": 321
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "ips":[
                {
                "id": 7370,
                "ip": "111.111.111.111",
                "type_id": 201
                },{
                "id": 7369,
                "ip": "5.134.220.54",
                "type_id": 201
                }
            ],
            "own_ip": "5.134.220.54",
            "is_auto_exception": false
        }
        
### Remove IP from exceptions [GET /api/ip/action.php?action=remove]

Получить список исключённых ip-адресов

+ Request (application/json)

        {
            "action": "remove",
            "id": 7370,
            "site_id": 321
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
### Add IP exception [GET /api/ip/action.php?action=create]

Добавление ip-адреса в исключение

+ Request (application/json)

        {
            "action": "create",
            "site_id": 321,
            "ip": "5.134.220.54"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "ips":[
                {
                "id": 7370,
                "ip": "5.134.220.54",
                "type_id": 201
                }
            ],
            "own_ip": "5.134.220.54"
        }
        
### Enable-Disable auto exception [GET /api/ip/action.php?action=auto_exception]

Включение/Отключение умной фильтрации по IP

+ Request (application/json)

        {
            "action": "auto_exception",
            "site_id": 321,
            "is_auto_exception": true
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "is_auto_exception": true
        }
        
## Analytics [/api/reports/visualize.php]

### Get reports list [GET /api/reports/types/action.php]

Получаем список отчётов


+ Request (application/json)

        {
            "action": "get",
            "visual": true,
            "extra_data": true
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "types": [
                {
                    "id": 26,
                    "name": "Эффективность рекламных каналов",
                    "is_add_attr_model": true,
                    "is_add_group_by": true,
                    "is_source_data": true,
                    "is_total_row_value": true,
                    "columns": [
                    ],
                    "metrics": [
                    ],
                    "default_settings": {
                        "date_interval": 8,
                        "encoding": 1592,
                        "format": 1581,
                        "graph_type": "spline",
                        "group_by": 30104
                    },
                    "report_group_type_id": 1601,
                    "x_axis_name": "",
                    "report_periods": [
                        {
                            "id": 30101,
                            "name": "по дням"
                        },
                        {
                            "id": 30102,
                            "name": "по месяцам"
                        },
                        {
                            "id": 30104,
                            "name": "по неделям"
                        }
                    ]
                }
            ]
        }

### Get report data [GET /api/report/visualize.php]

Получение данных для отчёта


+ Request (application/json)

        {
            "download_type": 0,
            "report_type_id": 19,
            "selected_columns": [
                {
                    "id": 34,
                    "name": "Тип трафика",
                    "is_required": false
                }
            ],
            "selected_metrics": [
                {
                    "id": 92,
                    "is_percent_view": false,
                    "is_required": false,
                    "is_sum": true,
                    "is_active": true,
                    "name": "Все обращения",
                    "order": "desc"
                }
            ],
            "selected_rows": [],
            "site_id": 156,
            "dates":{
                "to": "28.02.2017",
                "from": "01.02.2017"
            },
            "user_report_id": 0,
            "magic_string": "",
            "settings": {
                "is_include_vat": false,
                "set_top_rows": true,
                "attr_model": 5001,
                "group_by": 30104
            },
            "plot_option":{
                "type": "spline"
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "all_rows": [
                {
                    "code": "0_0_0",
                    "col1": "Всего",
                    "col1_id": 0,
                    "col2": "",
                    "col2_id": 0,
                    "col3": "",
                    "col3_id": 0,
                    "is_select": false,
                    "level_id": 1,
                    "max_value": 4.9680,
                    "name": "Всего",
                    "name_full": "Всего",
                    "p_code": null,
                    "values": [
                        {
                            "abs": "295.0",
                            "percent": "100"
                        },
                        {
                            "abs": "133.0",
                            "percent": "100"
                        },
                        {
                            "abs": "4.9",
                            "percent": "100"
                        }
                    ]
                }
            ],
            "chart_data": [],
            "selected_columns": [
                {
                    "id": 34,
                    "name": "Тип трафика"
                }
            ],
            "selected_metrics": [
                {
                    "id": 92,
                    "agg_type": "sum",
                    "is_active": false,
                    "name": "Все обращения",
                    "value_for_table": "round({%VALUE%},1)",
                    "is_percent_view": true
                    
                }
            ],
            "user_report_id": 12120,
            "magic_string": "",
            "dates":{
                "to": "28.02.2017",
                "from": "01.02.2017",
                "start_date": "24.06.2016"
            },
            "settings": {
                "is_set_top_rows": true,
                "attr_model": 5001,
                "group_by": 30104
            },
            "plot_option":{
                "type": "spline",
                "x_axis": [],
                "max_y_axis": 0
            }
        }

## Big Report [/api/reports/bigreport/action.php]

### Get Big Report config [GET /api/reports/bigreport/action.php?action=get]

Получаем конфигурацию всех отчётов по сайту

+ Request (application/json)

        {
            "action": "get",
            "site_id": 89
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "reports": [
                {
                    "id": 10,
                    "name": "Большой отчёт",
                    "pages": [
                        {
                            "id": 10,
                            "name": "Динамика",
                            "report_type_id": 14,
                            "is_include_vat": true,
                            "selected_column_id": 0,
                            "selected_metrics": [92, 93, 122, 133, 135],
                            "attr_model": 0,
                            "group_by": 30101
                        }
                    ]
                }
            ]
        }

### Get one Big Report config [GET /api/reports/bigreport/action.php?action=get&id=]

Получаем конфигурацию одного отчёта

+ Request (application/json)

        {
            "action": "get",
            "site_id": 89,
            "id": 10
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "reports": {
                    "id": 10,
                    "name": "Большой отчёт",
                    "pages": [
                        {
                            "id": 10,
                            "name": "Динамика",
                            "report_type_id": 14,
                            "is_include_vat": true,
                            "selected_column_id": 0,
                            "selected_metrics": [92, 93, 122, 133, 135],
                            "attr_model": 0,
                            "group_by": 30101
                        }
                    ]
                }
        }
        


### Save Big Report [GET /api/reports/bigreport/action.php?action=save]

Сохраняем название отчёта

+ Request (application/json)

        {
            "action": "save",
            "site_id": 156,
            "report": {
                    "id": 10,
                    "name": "Большой отчёт"
                }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "report": {
                    "id": 10,
                    "name": "Большой отчёт"
                }
        }


### Run Big Report [GET /api/reports/bigreport/action.php?action=run]

Запускаем выполнение отчёта

+ Request (application/json)

        {
            "action": "run",
            "site_id": 89,
            "id": 10,
            "filters": {
                "dates": {
                    "from": "20.07.2017",
                    "to": "26.07.2017"
                }
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "link": "http://ak.dev.vector.xpkg.ru/user_reports/v1.xlsx"
        }
        
### Save Page to Big Report  [GET /api/reports/bigreport/page/action.php?action=save]

Сохраняем конфигурацию страницы в отчёте

+ Request (application/json)

        {
            "action": "save",
            "site_id": 156,
            "report_id": 10,
            "page": {
                    "id": 10,
                    "name": "Динамика",
                    "report_type_id": 14,
                    "is_include_vat": true,
                    "selected_column_id": 0,
                    "selected_metrics": [92, 93, 122, 133, 135],
                    "attr_model": 0,
                    "group_by": 30101,
                    "magic_string": ""
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "report_id": 10,
            "page": {
                    "id": 10,
                    "name": "Динамика",
                    "report_type_id": 14,
                    "is_include_vat": true,
                    "selected_column_id": 0,
                    "selected_metrics": [92, 93, 122, 133, 135],
                    "attr_model": 0,
                    "group_by": 30101,
                    "magic_string": ""
            }
        }
        
### Remove Page from Big Report  [GET /api/reports/bigreport/page/action.php?action=remove]

Удаляем страницу из отчёта

+ Request (application/json)

        {
            "action": "remove",
            "site_id": 156,
            "report_id": 10,
            "page_id": 10
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
### Save Order Page for Big Report [GET /api/reports/bigreport/page/action.php?action=set_order]

Сохраняем сортировку страниц отчёта

+ Request (application/json)

        {
            "action": "set_order",
            "site_id": 156,
            "report_id": 10,
            "page_ids": [10, 11, 12, 13]
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
        
## SIP ID [/api/sip/action.php]



### SIP IDs config [GET /api/sip/action.php?action=get]

Получаем список SIP

+ Request (application/json)

        {
            "action": "get",
            "site_id": 89
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "sips": [
                        {
                            "id": 10,
                            "name": "Алексей",
                            "sip_id": 883140779189701,
                            "password": "2Je35iU4Y4",
                            "mtt_phones_history_id": 10,
                            "user_id": 5,
                            "start_date": "20.07.2017",
                            "end_date": "20.07.2017",
                            "count_redirect_scripts": 2
                        }
                    ]
        }
        


### SIP ID config [GET /api/sip/action.php?action=get&id=]
Данные по одному SIP

+ Request (application/json)

        {
            "action": "get",
            "site_id": 89,
            "id": 2
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "sip": {
                            "id": 10,
                            "name": "Алексей",
                            "sip_id": 883140779189701,
                            "password": "2Je35iU4Y4",
                            "mtt_phones_history_id": 10,
                            "user_id": 5,
                            "start_date": "20.07.2017",
                            "end_date": "20.07.2017",
                            "count_redirect_scripts": 2,
                            "redirect_scripts":[
                                {
                                    "id": 10,
                                    "name": "Базовый сценарий"
                                }
                            ]
                        }
        }

### Save SIP ID config  [GET /api/sip/action.php?action=save]

Сохранение данных по SIP

+ Request (application/json)

        {
            "action": "save",
            "site_id": 89,
            "sip": {
                    "id": 10,
                    "name": "Алексей"
                }
            
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "sip": {
                    "id": 10,
                    "name": "Алексей",
                    "sip_id": 883140779189701,
                    "password": "2Je35iU4Y4",
                    "mtt_phones_history_id": 10,
                    "user_id": 5,
                    "start_date": "20.07.2017",
                    "end_date": "20.07.2017"
                }
        }
        
### Remove SIP ID  [GET /api/sip/action.php?action=remove]

Удаляем SIP из проекта

+ Request (application/json)

        {
            "action": "remove",
            "site_id": 156,
            "id": 2
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        

## Integrations [/api/integrations/action.php]

### Get integrations list [GET /api/external/integrations/action.php?action=get]

Получаем список интеграции

+ Request (application/json)

        {
            "action": "get",
            "site_id": 156
        }

        
+ Response 200 (text/javascript)

        {
            "error": null,
            "integrations":[
                {
                    "active_dt": "",
                    "check_active_dt": "",
                    "hash": "d9bbcef1196ccddeaf521f7457201f2d",
                    "id": 7,
                    "is_send_calls": false,
                    "is_send_leads": false,
                    "is_send_cbs": false,
                    "is_send_objective": false,
                    "login": "martin.dvigus@gmail.com",
                    "oauth": "",
                    "state": true,
                    "subdomain": "martinholland",
                    "type_id": 1622,
                    "count_errors": 0
                }
            ]
        }
        
### Get integration info [GET /api/external/integrations/action.php?action=get&integration_id=]

Получаем данные по одной интеграции

+ Request (application/json)

        {
            "action": "get",
            "site_id": 156,
            "integration_id": 15
        }

        
+ Response 200 (text/javascript)

        {
            "error": null,
            "integration":{
                    "active_dt": "",
                    "check_active_dt": "",
                    "hash": "d9bbcef1196ccddeaf521f7457201f2d",
                    "id": 15,
                    "is_send_calls": false,
                    "is_send_leads": false,
                    "is_send_cbs": false,
                    "is_send_objective": false,
                    "login": "martin.dvigus@gmail.com",
                    "oauth": "",
                    "state": true,
                    "subdomain": "martinholland",
                    "type_id": 1622,
                    "count_errors": 0
            }
        }
        
### Save integration  [GET /api/external/integrations/action.php/action=save]

Создаём или Сохраняем настройки интеграции

+ Request (application/json)

        {
            "action": "save",
            "site_id": 89,
            "integration":{
                    "id": 7,
                    "type_id": 1622,
                    "subdomain": "martinholland",
                    "hash": "d9bbcef1196ccddeaf521f7457201f2d",
                    "login": "martin.dvigus@gmail.com",
                    "is_send_calls": false,
                    "is_send_leads": false,
                    "is_send_cbs": false,
                    "state": true
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "integration":{
                    "id": 7,
                    "type_id": 1622,
                    "subdomain": "martinholland",
                    "hash": "d9bbcef1196ccddeaf521f7457201f2d",
                    "login": "martin.dvigus@gmail.com",
                    "is_send_calls": false,
                    "is_send_leads": false,
                    "is_send_cbs": false,
                    "state": true
            }
        }
        
### Set integration state  [GET /api/external/integrations/action.php/action=set_state]

Меняем статус интеграции

+ Request (application/json)

        {
            "action": "set_state",
            "site_id": 89,
            "integration_id": 7,
            "state": true
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "integration":{
                    "id": 7,
                    "type_id": 1622,
                    "subdomain": "martinholland",
                    "hash": "d9bbcef1196ccddeaf521f7457201f2d",
                    "login": "martin.dvigus@gmail.com",
                    "is_send_calls": false,
                    "is_send_leads": false,
                    "is_send_cbs": false,
                    "state": true
            }
        }
        
### Get stats for interval  [GET /api/external/integrations/action.php/action=get_stats]

Скачать стат. данные за интервал дат

+ Request (application/json)

        {
            "action": "get_stats",
            "site_id": 89,
            "integration_id": 7,
            "dates": {
                "from": "05.04.2017",
                "to": "27.04.2017"
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
        
## Agreements [/api/user/agreement/action.php]

### Get agreements list [GET /api/user/agreement/action.php?action=get]

Получаем список договоров

+ Request (application/json)

        {
            "action": "get",
            "site_id": 321
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "agreements":[
                {
                    "id": 7,
                    "type_id": 5501,
                    "is_paper": false,
                    "document": "agreement_text",
                    "state": true,
                    "code": "VECTOR 1/163",
                    "dates":{
                        "to": "28.02.2017",
                        "from": "01.02.2017"
                    }
                }
            ]
        }
        
### Download agreement  [GET /api/pdf/action.php?action=download_agreement]

Скачать pdf договора

+ Request (application/json)

        {
            "action": "download_agreement",
            "id": 5
        }
        
+ Response 200 (application/pdf)


        
## Admin. Projects [/api/site/action.php?action=get_for_accountant]

### Get projects list [GET /api/site/action.php?action=get_for_accountant]

Получаем список Проектов

+ Request (application/json)

        {
            "action": "get_for_accountant",
            "magic_string": "",
            "owner_id": 5,
            "limit": 25
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "sites":[
                {
                    "access": 0,
                    "balance": -11423,
                    "branch_id": 1051,
                    "code": 174502,
                    "deals": {
                        "new": 14, 
                        "total": 14, 
                        "objective": 0
                        },
                    "description": "Тестовый сервер Леха не правь пока!!!",
                    "discount": 0,
                    "id": 2,
                    "is_favorite": 0,
                    "month_credit": 1127,
                    "name": "smtr2.dvigus.bget.ru",
                    "new_deals": 14,
                    "owner_id": 5,
                    "phone": 74959840823,
                    "role": null,
                    "state": {
                        "id": 601, 
                        "name": "Активен"
                        },
                    "theme_id": 5402,
                    "url": "http://smtr2.dvigus.bget.ru"
                }
            ]
        }
        
### Get project info [GET /api/site/action.php?action=get_for_accountant&site_id=]

Получаем информацию по конкретному проекту

+ Request (application/json)

        {
            "action": "get_for_accountant",
            "magic_string": "",
            "limit": 25,
            "site_id": 2
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "sites": [
                {
                "access": 0,
                "balance": -11423,
                "branch_id": 1051,
                "code": 174502,
                "deals": {
                    "new": 14, 
                    "total": 14, 
                    "objective": 0
                    },
                "description": "Тестовый сервер Леха не правь пока!!!",
                "discount": 0,
                "id": 2,
                "is_favorite": 0,
                "month_credit": 1127,
                "name": "smtr2.dvigus.bget.ru",
                "new_deals": 14,
                "owner_id": 5,
                "phone": 74959840823,
                "role": null,
                "state": {
                    "id": 601, 
                    "name": "Активен"
                    },
                "theme_id": 5402,
                "url": "http://smtr2.dvigus.bget.ru"
                }
            ]
        }
        
### Get permissions list [GET /api/user/permissions/action.php?action=get_for_accountant]

Получаем информацию по доступам к конкретному проекту

+ Request (application/json)

        {
            "action": "get_for_accountant",
            "site_id": 2
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "accesses": [
                {
                    "id": 2521,
                    "rank": 1,
                    "permission_id": 1013,
                    "user": {
                        "email": "alexey.maslov@dvigus.ru",
                        "is_invited": true,
                        "is_owner": false,
                        "name": "Маслов А.В.",
                        "phone": "+7 963 978 58 97"
                    }
                }
            ]
        }
        
### Set deal processing for project [GET /api/site/action.php?action=set_deal_processing]

Распределяем обращения между системными операторами. Запускаем процедуру set_deal_processing__site(in in_site_id int)

+ Request (application/json)

        {
            "action": "set_deal_processing",
            "site_id": 2
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
## Admin. Users [/api/user/action.php?action=get_for_accountant]

### Get users list [GET /api/user/action.php?action=get_for_accountant]

Получаем список Проектов

+ Request (application/json)

        {
            "action": "get_for_accountant"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "users":[
                {
                    "balance": -11423,
                    "company_name": "",
                    "email": "support@vectoranalytics.ru",
                    "id": 1,
                    "is_accountant": true,
                    "is_developer": true,
                    "is_system_operator": false,
                    "is_verified_account": true,
                    "is_verified_email": true,
                    "is_verified_phone": false,
                    "name": "Служба поддержки",
                    "overdraft": 0,
                    "phone_int": 74959840823,
                    "telegram_chat_id": 254203930,
                    "token_phone": 0
                }
            ]
        }
        
### Get system operator list [GET /api/user/action.php?action=get_system_operators]

Получаем список Проектов

+ Request (application/json)

        {
            "action": "get_system_operators"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "users":[
                {
                    "balance": -11423,
                    "company_name": "",
                    "email": "support@vectoranalytics.ru",
                    "id": 1,
                    "is_accountant": true,
                    "is_developer": true,
                    "is_system_operator": true,
                    "is_favorite": 0,
                    "is_verified_account": true,
                    "is_verified_email": true,
                    "is_verified_phone": false,
                    "name": "Служба поддержки",
                    "overdraft": 0,
                    "phone_int": 74959840823,
                    "telegram_chat_id": 254203930,
                    "token_phone": 0
                }
            ]
        }
        
        
### Reset user password [GET /api/user/action.php?action=reset_password]

Сбросить пароль для пользователя

+ Request (application/json)

        {
            "action": "reset_password",
            "user_id": 5
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
### Delete user sessions [GET /api/user/action.php?action=delete_sessions]

Удалить все сессии пользователя

+ Request (application/json)

        {
            "action": "delete_sessions",
            "user_id": 5
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
## Admin. Phones [/api/phones/action.php?action=get_for_accountant]

### Get phones list [GET /api/phones/action.php?action=get_for_accountant]

Получаем список всех номеров

+ Request (application/json)

        {
            "action": "get_for_accountant"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "phones":[
                {
                    "id": 1,
                    "phone_int": 7495123467,
                    "start_date": "2017-01-01 10:00:00",
                    "end_date": "",
                    "state": 1
                }
            ]
        }
        
## Admin. Exceptions [/api/exceptions/action.php]

### Get system exceptions [GET /api/exceptions/action.php?action=get_system_exceptions]

Получаем системный чёрный список номеров телефонов

+ Request (application/json)

        {
            "action": "get_system_exceptions",
            "type_id": 3
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "exceptions":[
                {
                    "id": 1,
                    "type_id": 3,
                    "phone_int": 7495123467,
                    "dt": "2017-01-01 10:00:00"
                }
            ]
        }
        
### Add system exception [GET /api/exceptions/action.php?action=add_system_exception]

Добавить номер телефона в системный чёрный список

+ Request (application/json)

        {
            "action": "add_system_exception",
            "type_id": 3
            "phone_int": 7495123467
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "exception":
                {
                    "id": 1,
                    "type_id": 3,
                    "phone_int": 7495123467,
                    "dt": "2017-01-01 10:00:00"
                }
        }
        
### Delete system exception [GET /api/exceptions/action.php?action=remove_system_exception]

Удалить номер телефона из системного чёрного списка

+ Request (application/json)

        {
            "action": "remove_system_exception",
            "id": 10
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }

## User permissions [/api/users/permissions/action.php]

### Get user permissions list [GET /api/users/permissions/action.php?action=get]
Получаем список пользователей

+ Request (application/json)

        {
            "action": "get",
            "site_id": 321
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "accesses": [
                {
                    "id": 2521,
                    "permission_id": 1013,
                    "rank": 1,
                    "user": {
                        "user_id": 5,
                        "email": "alexey.maslov@dvigus.ru",
                        "is_invited": true,
                        "is_owner": false,
                        "name": "Маслов А.В.",
                        "phone": "+7 963 978 58 97"
                    }
                }
            ]
        }
        
### Add/Update user permission [GET /api/users/permissions/action.php?action=create]
Добавляем пользователя к проекту / меняем пользователя

+ Request (application/json)

        {
            "action": "save",
            "site_id": 321,
            "access": {
                "id": 3015,
                "permission_id": 1013,
                "rank": 1,
                "user": {
                    "email": "alexey.maslov@dvigus.ru",
                    "is_invited": true,
                    "is_owner": false,
                    "name": "Маслов А.В.",
                    "phone": "+7 963 978 58 97"
                }
            },
            "is_notify_user": true
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "access": {
                "id": 2521,
                "permission_id": 1011,
                "rank": 1,
                "user": {
                    "email": "alexey.maslov@dvigus.ru",
                    "is_invited": true,
                    "is_owner": false,
                    "name": "Маслов А.В.",
                    "phone": "+7 963 978 58 97"
                }
            }
        }
        
### Remove user permission [GET /api/users/permissions/action.php?action=remove]
Удаляем пользователя из проекта

+ Request (application/json)

        {
            "action": "remove",
            "site_id": 321,
            "access_id": 3304
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
## VectorPromocode [/api/promocode/action.php]

### Get promocodes [GET /api/promocode/action.php?action=get]
Получаем список промокодов

+ Request (application/json)

        {
            "action": "get",
            "filters":{
                "user_id": 5,
                "name": "VECTORAWESOME",
                "dates":{
                    "to": "28.02.2017",
                    "from": "01.02.2017"
                },
                "is_active": true
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "promocodes": [
                {
                    "id": 23,
                    "name": "VECTORAWESOME",
                    "user_id": 5,
                    "dates":{
                        "to": "28.02.2017",
                        "from": "01.02.2017"
                    },
                    "duration": 14,
                    "value": 1000,
                    "is_active": true
                }
            ]
        }
        
### Generate & Save promocode [GET /api/promocode/action.php?action=save]
Генерируем и сохраняем промокод

+ Request (application/json)

        {
            "action": "save",
            "promocode": {
                "id": null,
                "name": "VECTORAWESOME",
                "user_id": 5,
                "dates":{
                    "to": "28.02.2017",
                    "from": "01.02.2017"
                },
                "duration": 14,
                "value": 1000,
                "is_active": true
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "promocode": {
                "id": 23,
                "name": "VECTORAWESOME",
                "user_id": 5,
                "dates":{
                    "to": "28.02.2017",
                    "from": "01.02.2017"
                },
                "duration": 14,
                "value": 1000,
                "is_active": true
            }
        }

### Add promocode [GET /api/user/promocode/action.php?action=add]
Пользователь добавляет промокод. Возможные статусы: промокод применён, промокод не найден, истёк срок действия промокода, данный промокод уже был использован

+ Request (application/json)

        {
            "action": "add",
            "name": "VECTORAWESOME"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "promocode": {
                "id": 23,
                "name": "VECTORAWESOME",
                "user_id": 5,
                "dates":{
                    "to": "28.02.2017",
                    "from": "01.02.2017"
                },
                "value": 1000,
                "is_active": true
            }
        }
        
### Get list promocodes for user [GET /api/user/promocode/action.php?action=get]
Получаем список промокодов для пользователя

+ Request (application/json)

        {
            "action": "get"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "promocodes": [
                {
                    "id": 23,
                    "name": "VECTORAWESOME",
                    "user_id": 5,
                    "dates":{
                        "to": "28.02.2017",
                        "from": "01.02.2017"
                    },
                    "value": 1000,
                    "is_active": true
                }
            ]
        }
        
### Remove promocode for user [GET /api/user/promocode/action.php?action=remove]
Получаем список промокодов для пользователя

+ Request (application/json)

        {
            "action": "remove",
            "id": 23
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
## Import data [/api/import/action.php]

### Get list import data [GET /api/import/action.php?action=get]
Получаем список загруженных файлов

+ Request (application/json)

        {
            "action": "get",
            "site_id": 156
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "import_datas": [
                {
                    "id": 1,
                    "name": "2017.06.14 - Импорт данных Голландский квартал.csv",
                    "user_id": 5,
                    "count_rows": 1000,
                    "count_upload_rows": 1000,
                    "is_active": true,
                    "dt": "2017-04-27 19:41:49"
                }
            ]
        }
        
### Remove import data [GET /api/import/action.php?action=remove]
Удаляем загруженные данные

+ Request (application/json)

        {
            "action": "remove",
            "site_id": 156,
            "import_data":{
                "id": 1
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }

### Get Ads Tree [GET /api/tree/action.php?action=get]
Получаем Рекламное дерево

+ Request (application/json)

        {
            "action": "get",
            "site_id": 156
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "edges": [
                {
                    "id": 2,
                    "pid": 1,
                    "name": "Платный трафик",
                    "exp_import": "",
                    "exp_vector": " traffic_type_id=30006 ",
                    "user_id": 5,
                    "dt": "2017-04-27 19:41:49"
                }
            ]
        }
        
### Add Edge for Ads Tree [GET /api/tree/action.php?action=save]
Сохраняем или добавляем узел для дерева

+ Request (application/json)

        {
            "action": "save",
            "site_id": 156,
            "edge":{
                "id": 3,
                "pid": 1,
                "name": "Поисковый трафик",
                "exp_import": "",
                "exp_vector": " traffic_type_id=30002 ",
                "user_id": 5
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "edges": [
                {
                    "id": 3,
                    "pid": 1,
                    "name": "Поисковый трафик",
                    "exp_import": "",
                    "exp_vector": " traffic_type_id=30002 ",
                    "user_id": 5,
                    "dt": "2017-04-27 19:41:49"
                }
            ]
        }
        
### Delete Edge for Ads Tree [GET /api/tree/action.php?action=delete]
Удаляем узел для дерева

+ Request (application/json)

        {
            "action": "delete",
            "site_id": 156,
            "edge":{
                "id": 3
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
## Account [/api/user/account/action.php]

### Account [GET /api/user/account/action.php?action=delete_sessions]

Разлогиниться на всех устройствах

+ Request (application/json)

        {
            "action": "delete_sessions"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null
        }
        
## Apps [/api/user/app/action.php]

### Get apps list [GET /api/user/app/action.php?action=get]

Вывести список собственных приложений

+ Request (application/json)

        {
            "action": "get"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "apps": [
                {
                    "id": 1,
                    "name": "Marilyn",
                    "description": "Система автоматизации интернет-рекламы",
                    "app_link": "https://mymarilyn.ru/",
                    "callback_url": "https://mymarilyn.ru/token",
                    "client_id": "0d07c30a399ffd893b59ca770ded0b6c",
                    "start_date": "12.10.2017 19:05:29",
                    "end_date": ""
                }
            ]
        }
        
### Create app [GET /api/user/app/action.php?action=create]

Создать собственное приложение

+ Request (application/json)

        {
            "action": "create",
            "app": {
                    "name": "Marilyn",
                    "description": "Система автоматизации интернет-рекламы",
                    "app_link": "https://mymarilyn.ru/",
                    "callback_url": "https://mymarilyn.ru/token"
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "app": {
                    "id": 1,
                    "name": "Marilyn",
                    "description": "Система автоматизации интернет-рекламы",
                    "app_link": "https://mymarilyn.ru/",
                    "callback_url": "https://mymarilyn.ru/token",
                    "client_id": "0d07c30a399ffd893b59ca770ded0b6c",
                    "start_date": "12.10.2017 19:05:29",
                    "end_date": ""
            }
        }
        
### Save app [GET /api/user/app/action.php?action=save]
        
Сохранить приложение

+ Request (application/json)

        {
            "action": "save",
            "app": {
                    "id": 1,
                    "name": "Marilyn",
                    "description": "Система автоматизации интернет-рекламы",
                    "app_link": "https://mymarilyn.ru/",
                    "callback_url": "https://mymarilyn.ru/token"
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "app": {
                    "id": 1,
                    "name": "Marilyn",
                    "description": "Система автоматизации интернет-рекламы",
                    "app_link": "https://mymarilyn.ru/",
                    "callback_url": "https://mymarilyn.ru/token",
                    "client_id": "0d07c30a399ffd893b59ca770ded0b6c",
                    "start_date": "12.10.2017 19:05:29",
                    "end_date": ""
            }
        }
        
### Delete app [GET /api/user/app/action.php?action=delete]
        
Удалить приложение

+ Request (application/json)

        {
            "action": "delete",
            "app": {
                    "id": 1
            }
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "app": {
                    "id": 1,
                    "name": "Marilyn",
                    "description": "Система автоматизации интернет-рекламы",
                    "app_link": "https://mymarilyn.ru/",
                    "callback_url": "https://mymarilyn.ru/token",
                    "client_id": "0d07c30a399ffd893b59ca770ded0b6c",
                    "start_date": "12.10.2017 19:05:29",
                    "end_date": "12.12.2017 19:05:29"
            }
        }
        
### Get list external apps [GET /api/user/app/external/action.php?action=get]
        
Получить список приложений которым предоставлен доступ

+ Request (application/json)

        {
            "action": "get"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "external_apps": [
                {
                    "id": 10,
                    "token": "ef59f56f8431e7ce392feaee1be919b5",
                    "app": {
                        "id": 1,
                        "name": "Marilyn",
                        "description": "Система автоматизации интернет-рекламы",
                        "app_link": "https://mymarilyn.ru/",
                        "start_date": "12.10.2017 19:05:29",
                        "end_date": ""
                    }
                }
            ]
        }
        
### Get app info [GET /api/user/app/external/action.php?action=get_by_client_id]

Получить инфо по внешнему приложению

+ Request (application/json)

        {
            "action": "get_by_client_id",
            "client_id": "0d07c30a399ffd893b59ca770ded0b6c"
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "app": {
                    "id": 1,
                    "name": "Marilyn",
                    "description": "Система автоматизации интернет-рекламы",
                    "app_link": "https://mymarilyn.ru/",
                    "callback_url": "https://mymarilyn.ru/token",
                    "client_id": "0d07c30a399ffd893b59ca770ded0b6c",
                    "start_date": "12.10.2017 19:05:29",
                    "end_date": ""
            }
        }
        
### Grant access to external apps [GET /api/user/app/external/action.php?action=grant_access]
        
Предоставить доступ приложению к своим данным

+ Request (application/json)

        {
            "action": "grant_access",
            "app_id": 1
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "external_app": {
                "id": 10,
                "token": "ef59f56f8431e7ce392feaee1be919b5",
                "app": {
                    "id": 1,
                    "name": "Marilyn",
                    "description": "Система автоматизации интернет-рекламы",
                    "app_link": "https://mymarilyn.ru/",
                    "start_date": "12.10.2017 19:05:29",
                    "end_date": ""
                }
            }
        }
        
### Delete access to external apps [GET /api/user/app/external/action.php?action=delete_access]
        
Закрыть доступ приложению к своим данным

+ Request (application/json)

        {
            "action": "delete_access",
            "external_app_id": 10
        }
        
+ Response 200 (text/javascript)

        {
            "error": null,
            "external_app": {
                "id": 10,
                "token": "ef59f56f8431e7ce392feaee1be919b5",
                "app": {
                    "id": 1,
                    "name": "Marilyn",
                    "description": "Система автоматизации интернет-рекламы",
                    "app_link": "https://mymarilyn.ru/",
                    "start_date": "12.10.2017 19:05:29",
                    "end_date": "12.12.2017 19:05:29"
                }
            }
        }